name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'
      - name: Download deps
        run: go mod download
      - name: Test
        run: go test ./...